### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by zavatar** [leancloud/servlet-getting-started#5]
依照Readme中的步骤本地启动服务没问题，但lean deploy的时候出错：
`部署失败：The command '/bin/sh -c chown leanengine:leanengine . &&    su leanengine -c 'mvn dependency:tree'' returned a non-zero code: 1:`

**Comment by sdjcw** [comment]
你好，这看起来是下载依赖出了问题，麻烦重试下试试看。
